### ISSUE TITLE
auth0 login issue on safari and chrome

### ISSUE THREAD

**Issue by sumit-pandey** [auth0/auth0.js#1171] opened 2021-04-22 19:37 UTC
I am using the auth0-js package and since I am using embed using webAuth.login() function when I m trying login on safari it won't log me in most of the time I have also checked my network request when I try to log in it throws an error saying failed to load resource but sometimes it works for me. Also, I have seen the same issue in chrome as well but it's not that frequent

**Comment by stevehobbsdev** [comment] 2021-05-06 13:42
Thanks for your patience here @sumit-pandey. It's difficult to nail down the issue based on your report. Do you have any more detail from the network tab you can share? Also, can you see anything untoward in your [Auth0 Logs](https://manage.auth0.com/#/logs) that might help resolve what the problem is?

**Comment by icon-gaurav** [comment] 2021-05-20 11:08
We have the same issue on our platform, we did some changes in login function as managing the state variable on our side and it did actually work.

There is some scenarios where auth0 package didn't manage the state variable bcz of some cookies issues with safari (we didn't knew about this). So we store this variable in localstorage and then use it as we want.

Note :-- This state variable should be random at each and every login request

![image](https://user-images.githubusercontent.com/34798411/118968615-bdbefa80-b989-11eb-9112-e87688aeb4e7.png)


![image](https://user-images.githubusercontent.com/34798411/118968441-8fd9b600-b989-11eb-86c2-19cf995b629d.png)

**Comment by stevehobbsdev** [comment] 2021-06-18 15:52
Thanks for the insight @icon-gaurav.

I'll close this for the moment as I can't reproduce it based on the original report. Happy to reopen though if we get some more details and a repro to help us dive into it.

**Closed by stevehobbsdev** 2021-06-18 15:52 UTC
Labels: bug report, needs more info
