### ISSUE TITLE
>= v9.11.0 breaks sever side builds

### ISSUE THREAD

**Issue by zanettin** [auth0/auth0.js#964] opened 2019-07-09 12:07 UTC
In order to efficiently and accurately address your issue or feature request, please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. Please delete any sections or questions below that do not pertain to this request.

For general support or usage questions, please use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com.).

### Description

till v9.10.4 `auth0-js` could be built for server side environments w/o any issues. in the latest build this is no longer possible since it breaks the build chain because of a `window.fetch` call which is not able to be executed on server side (node) envs.

### Prerequisites

[x] I have checked the [documentation for this library](https://auth0.github.io/auth0.js/index.html).

[x] I have checked the [Auth0 Community](https://community.auth0.com/) for related posts.

[x] I have checked for related or duplicate [Issues](https://github.com/auth0/auth0.js/issues) and [PRs](https://github.com/auth0/auth0.js/pulls).

[x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).

[x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Environment

Please provide the following:

- Version of Auth0.js used: `9.11.0`
- Browser and OS version(s) affected: `node express server / webpack 4 bundling`
- Additional libraries or browser extensions being used that might affect behavior: `many but the issue should be easy reproducable`

### Reproduction

- create a js file
- include auth0-js
- run it through webpack with target set to `node`
- execute the script with node

result => `ReferenceError: window is not defined`
affected minified line of code: `at=window.fetch||(window.fetch=nt.default||nt)`

**Comment by luisrudge** [comment] 2019-07-09 14:46
duplicate of https://github.com/auth0/auth0.js/issues/959

**Closed by luisrudge** 2019-07-09 14:46 UTC
