### ISSUE TITLE
"`state` does not match" on IE10, using autogenerated state

### ISSUE THREAD

**Issue by williamgelhar-validere** [auth0/auth0.js#837] opened 2018-10-11 19:31 UTC
Using Auth0.js ^9.8.0. Login works fine on Chrome (v68 OSX), on IE10 (the Microsoft provided IE10WIN7 VM image) it works up until `parseHash`, where it fails from "`state` does not match".

If I generate a state and nonce and pass them in `authorize` and `parseHash`, it works. If I don't pass them in, it fails.

The auth0 WebAuth instance is constructed like this:

```js
const authInstance = new auth0.WebAuth({
        domain,
        clientID,
        redirectUri,
        audience: `[my API ID]`,
        responseType: 'token',
        scope: 'openid'
      })
```

the call to authorize:

`authInstance.authorize();`

the call to parseHash:
```js
    const parseHash = new Promise((resolve, reject) => {
      authInstance.parseHash((err, authResult) => {
        if (authResult && authResult.accessToken) {
          const { accessToken } = authResult;

          return resolve(authResult);
        } else if (err) {
          return reject(err);
        }
      });
    });
```

the redirectUri is the exact same as the originating URI, no difference at all (both use http, not https (developing locally), exact same IP and port).

The security settings on IE10 should allow for localStorage and cookies, and when I try manually generating the nonce+state, I save them to localStorage, so that part definitely works.

**Comment by luisrudge** [comment] 2018-10-11 19:36
is there a state in the /authorize request? I ask this because we don't auto generate a random value if the browser doesn't support native `crypto`: https://github.com/auth0/auth0.js/blob/master/src/helper/random.js#L9

**Comment by williamgelhar-validere** [comment] 2018-10-11 19:39
Seems to be a state being generated and coming through in the /authorize request:

`Request	GET /authorize?client_id=[client id]&response_type=token&redirect_uri=[redirect uri]&connection=Username-Password-Authentication&login_hint=[email]&state=-5mqeAzG4sxNM_tIpx6S1RCan7iOhGE3&sso=true&protocol=oauth2&scope=openid&audience=[api key]&auth0Client=[auth0Client]&_csrf=GqLY9Aip-gXsKAiyggP-CfEMWOQYU_svlCJE&_intstate=deprecated HTTP/1.1`

I checked out another github issue about this same thing, and it doesn't seem like the state is coming back to my callback URI in a query string.

**Comment by luisrudge** [comment] 2018-10-11 19:43
where's `_csrf` and `_intstate` coming from? are you using the hosted login page? do you have a step-by-step guide to reproduce this?

**Comment by williamgelhar-validere** [comment] 2018-10-11 19:52
Not sure where those two properties are coming from. Yes the hosted login page. 

I also went to the auth0 logout URL and tried the process again, the redirect to domain.auth0.com/authorize now looks like this:

`/authorize?client_id=[client id]&response_type=token&redirect_uri=[redirect_uri]&scope=openid&audience=[api id]&state=&auth0Client=[auth0Client]`

The state is now empty and the `_csrf` and `_intstate` are missing, so theres a good chance that something was using cached data. Starting from scratch, it looks like the state just wasn't being generated on IE10 (like you said).

The step by step guide is:
1. user visits my page, `authInstance.authorize();` is called
2. user is redirected to the auth0 hosted login page
3. user enters their login information
4. user is redirected back to my callback URL, parseHash is called

**Comment by luisrudge** [comment] 2018-10-11 19:54
ok, great. that query string matches what we generate (no extra params and empty state). Is the error still happening? When you're redirected BACK from Auth0 (step 4), do you get a `state` param in the url?

**Comment by williamgelhar-validere** [comment] 2018-10-11 19:57
Error is still happening yes, the redirect URL in step 4 is:

`http://192.168.87.80:4000/app/callback#access_token=[access_token]&expires_in=7200&token_type=Bearer`

no `state` param is coming through

**Comment by luisrudge** [comment] 2018-10-11 20:45
then, yeah. the code is throwing here: https://github.com/auth0/auth0.js/blob/master/src/web-auth/index.js#L230

We can't allow for an authentication response without a state parameter because we always generate one (when the browser supports it, of course). So you can either generate one for IE10 (if you're server rendering), or use a fixed one for SPAs. We can't bypass this check for security reasons.

**Closed by luisrudge** 2018-10-11 20:45 UTC
