### ISSUE TITLE
`renewAuth` is wrong if `postMessage` is called multiple times in iframe

### ISSUE THREAD

**Issue by rochdev** [auth0/auth0.js#428] opened 2017-05-09 18:04 UTC
When using `auth0.renewAuth()` with the `usePostMessage` options to `true`, the resulting `authResult` is wrong if `window.postMessage()` was called in the iframe before auth0 had the chance to call it.

In my case I have several Chrome extensions that are calling `postMessage` so `authResult` only contains information from (for example) React DevTools instead of being an actual authentication result.

I am using Auth0.js 8.6.1 on latest Chrome.

**Comment by luisrudge** [comment] 2017-05-09 18:33
this is a dupe of https://github.com/auth0/auth0.js/issues/406
We're aware and trying to think a way to fix this without a breaking change.

**Closed by luisrudge** 2017-05-09 18:33 UTC
