### ISSUE TITLE
Ignore messages that are not from Auth0's iframe

### ISSUE THREAD

**Issue by sandrinodimattia** [auth0/auth0.js#406] opened 2017-03-31 09:12 UTC
So renewAuth is not working for me with postMessage enabled. The request is getting cancelled in the browser. In the iframe it looks like other events are being sent (before the code reaches parseHash) which causes the iframe to be destroyed.

Now I have this when running locally (because of an event from webpack) and when running a deployed version (because of an empty event). Here is what fixed it for me in the iframe handler:

```js
IframeHandler.prototype.messageEventListener = function (e) {
  if (!e.data || e.data === '' || e.data.type === 'webpackOk') {
    return;
  }
  this.destroy();
  this.callbackHandler(e.data);
};
```

**Comment by luisrudge** [comment] 2017-03-31 14:42
This is in our backlog. We need to figure it out a way to ignore posted messages that are not from our iframe. I'll not add anything specific to webpack at the moment, but this will be fixed in the near future

**Comment by oyvinmar** [comment] 2017-04-05 11:16
We are having the same issue with Redux Devtools, so a general solution would be appreciated.

**Comment by luisrudge** [comment] 2017-04-05 14:13
It will be general. We'll probably prefix our own messages with `auth:[...]` and check for that prefix before destroying.

**Comment by bragma** [comment] 2017-04-12 12:44
Just found out this huge problem. It seems that facebook's SDK causes renewAuth's callback to be triggered without error but the response contains invalid data.

**Comment by lina128** [comment] 2017-04-14 14:40
Same issue here.

**Comment by luisrudge** [comment] 2017-04-14 16:47
Hey.. Can any of you create a repro project so I can test this? I know what the problem is, but I can't reproduce it 😭

**Comment by lina128** [comment] 2017-04-14 18:22
I use this react redux starter kit: https://github.com/davezuko/react-redux-starter-kit
The message includes data of the following format:
{ ..., source: '@devtools-extension' } or { ..., source: '@devtools-page' }

I'll try to create a repro project.

**Comment by luisrudge** [comment] 2017-04-14 18:42
Thanks. I don't know if we can effectively fix this at all. We don't have control on how the messages are posted... 


```js
    // this code goes inside the callback.html file (or your callback route)
    auth0.parseHash(window.location.hash, function (err, data) {
      parent.postMessage(err || data, "http://localhost:3000/");
    });
``` 

Since this code lives outside of auth0.js, there's no way to know if the message is coming from the callback itself or from elsewhere.

**Comment by lina128** [comment] 2017-04-14 18:46
Is it possible to enrich the data somehow? Like data.source = 'auth0'. It will be along the line of your previous thoughts: 'prefix our own messages with auth:[...]'.

**Comment by luisrudge** [comment] 2017-04-14 18:47
nope, because this code lives outside of auth0.js. This is custom code that users write.

**Comment by lina128** [comment] 2017-04-14 18:52
This code is auth0's code, right?
IframeHandler.prototype.messageEventListener = function (e) {
  this.destroy();
  this.callbackHandler(e.data);
};

why not check the data source before destroying? Like Sandrinodimattia add this line before destroying:
if (!e.data || e.data === '' || e.data.type === 'webpackOk') {
    return;
 }

In my case, I need to add this:
if (!e.data || e.data === '' || e.data.source === '@devtools-extension' || e.data.source === '@devtools-page') {
	    return;
	  }

For this to be solved for general cases, shouldn't the code just add a data.source or something and check that before destroying?

**Comment by luisrudge** [comment] 2017-04-14 18:58
This is auth0's code, yes.
But here's the thing.

For a webpack fix, we'd need to add:
`if (!e.data || e.data === '' || e.data.type === 'webpackOk')`

For a redux dev tools fix, we'd need to add:
`if (!e.data || e.data === '' || e.data.source === '@devtools-extension' || e.data.source === '@devtools-page')`

This won't scale, because lots of iframes sends data via postMessage. There's no way we blacklist every possible type of message that can happen.

**Comment by bragma** [comment] 2017-04-14 19:00
You have no control on others' code but the silent callback page is under control of the developer so he can enrich (ex: Add a string) the posted message. Then you can allow to specify the same string on renewAuth's options. When handling posted data, if the configured data is missing you ignore it.
There are a few assumptions here about parsability of unknown messages, but with a try/catch you can ignore errors.

**Comment by luisrudge** [comment] 2017-04-14 19:06
Yeah, that will work, but the best way is to receive something from the back end that we can check, so the developer won't need to do anything.
There's some working being made in the back end related to this. Once that is done, we can properly implement this check.

**Comment by bragma** [comment] 2017-04-15 14:48
Good to know it will be fixed soon! At the moment I had to delay Facebook's SDK initialization to avoid getting unwnated posts.
I am not sure it's a good idea, but maybe the "state" field of the request may be leveraged? It is required for it to be something unique and the response should already be ignored if the state is unknown, so maybe it can be used to know if the post is required, i.e. if the state matches.

**Comment by luisrudge** [comment] 2017-04-16 01:17
Yeah.. there are a few alternatives to fix this in our client, but this will be better handled in the back end. I'm not sure what's the ETA on that, but it's coming.

**Comment by buccfer** [comment] 2017-04-20 19:52
Mmm the data comes from the parseHash function. Maybe it should include in the data object a "source" property with some specific value. And in the iframe handler check the source before destroying.

**Comment by buccfer** [comment] 2017-04-20 20:12
**web-auth/index.js**

`function buildParseHashResponse(qsParams, appStatus, token) {
  return {
    accessToken: qsParams.access_token || null,
    idToken: qsParams.id_token || null,
    idTokenPayload: token || null,
    appStatus: appStatus || null,
    refreshToken: qsParams.refresh_token || null,
    state: qsParams.state || null,
    expiresIn: qsParams.expires_in ? parseInt(qsParams.expires_in, 10) : null,
    tokenType: qsParams.token_type || null,
    _source: 'auth0js'
  };
}`

**helper/iframe-handler.js**

`IframeHandler.prototype.messageEventListener = function (e) {
  if (!e.data || !e.data._source === 'auth0js') {
    return;
  }
  this.destroy();
  this.callbackHandler(e.data);
};`

**Comment by rochdev** [comment] 2017-05-09 20:28
I've seen a similar pattern to what @buccfer is proposing in several other libraries. Here is an [example](https://github.com/hapijs/joi/blob/master/lib/errors.js#L52). With this pattern both `data` and `err` would get an `isAuth0` property to `true`.

**Comment by aaronchilcott** [comment] 2017-05-11 07:16
I have just discovered this issue too. 

My $0.02:

Allow the Iframe helper to accept an event processor which return true if the desired event was found or false otherwise. I don't think it's really the responsibility of the Iframe helper to decide if the event is the one we're looking for or not. Instead, the main auth0 logic should do that. 

It would be super nice if we could overload that too, so we could customise it a bit more...

**Comment by Doeke** [comment] 2017-06-04 11:23
Doesn't the undocumented option `postMessageDataType` do what is needed (filtering incoming postMessages)?

Anyhow, in my case I ended up just not using `postMessage` for the silent callback, which seems to work fine even though the docs is not very clear on this.

**Comment by luisrudge** [comment] 2017-06-04 17:15
This was fixed in https://github.com/auth0/auth0.js/pull/432 - it's still not documented though.

**Closed by luisrudge** 2017-06-04 17:15 UTC

**Comment by gilesbutler** [comment] 2017-07-02 10:39
Hey @luisrudge any update on documentation around this?

I followed @oliverlloyd's suggestion from [#429](https://github.com/auth0/auth0.js/issues/429) but that didn't work.

We're still seeing `react-devtools` and `webpack` responses in the `authResult` on auth0-js 8.8.0.

**Comment by luisrudge** [comment] 2017-07-03 21:40
@gilesbutler Sorry, this is not in the docs yet. You have to use the `postMessageDataType` option.

```js
var auth0 = new auth0.WebAuth({
  domain: "{YOUR_AUTH0_DOMAIN}",
  clientID: "{YOUR_AUTH0_CLIENT_ID}",
  postMessageDataType: 'my-custom-data-type'
});
```

And then in your callback page, you have to call it like this:

```html
<!DOCTYPE html>
<html>

<head>
  <script type="text/javascript">
    parent.postMessage({
        hash: window.location.hash,
        type: 'my-custom-data-type'
    }, "https://localhost:3000/");
  </script>
</head>

<body></body>

</html>
```

**Comment by rochdev** [comment] 2017-07-03 23:06
What is the benefit of using `usePostMessage: true`?

**Comment by luisrudge** [comment] 2017-07-04 00:15
we listen to different events based on that param: https://github.com/auth0/auth0.js/blob/bdce0d5927dcf652b9ddbd3e9a1141c56002d774/src/web-auth/silent-authentication-handler.js#L18

**Comment by gilesbutler** [comment] 2017-07-04 11:10
Thanks for getting back to me @luisrudge unfortunately still can't get this to work. We're using React-router so our callback page is just a route that triggers a SilentCallback component...
```
{
setupAuth0() {
    this.auth0 = new auth0.WebAuth({
      domain: config.auth0.domain,
      clientID: config.auth0.clientID,
      postMessageDataType: 'auth0:silent-authentication',
      ...
    });
  }
}

<Route path="/auth/renew" component={SilentCallback} />

// SilentCallback.js
export default () => {
  const data = {
    hash: window.location.hash,
    type: 'auth0:silent-authentication',
  };

  window.parent.postMessage(data, "*");

  return null
}
```

This is how we're calling `renewAuth`, but the `redirectUri` is never actually hit. 
```
const nonce = this.randomString(16);

this.auth0.renewAuth({
      redirectUri: `${window.location.origin}/auth/renew`,
      usePostMessage: true,
      nonce,
    }, (err, authResult) => {
      if (err) {
        console.error(err);
        // The access_token is probably bad, remove it so we don't keep trying to renew it.
        localStorage.removeItem('access_token');
      } else if (hasProp(authResult, 'idToken') && decodeJwt(authResult.idToken).nonce !== nonce) {
        // Something fishy is going on.
        console.error('The nonce string returned did not match the one sent.')
        // Ensure user is asked to login again
        localStorage.removeItem('access_token');
      } else if (hasProp(authResult, 'idToken')) {
        // Save the returned session data to LS
        this.setSession(authResult);
      } else {
        console.log('Unexpected authResult:', authResult);
      }
    });
```

So `authResult` is still...
```
{
    source: "react-devtools-detector", 
    reactBuildType: "development"
}
```

**Comment by luisrudge** [comment] 2017-07-04 13:05
does your route gets called at all? does it work if you have just a static html page instead of letting react router handle that?

**Comment by buccfer** [comment] 2017-07-05 19:13
@luisrudge This is not working for us neither.

1. package.json
`"auth0-js": "^8.8.0"`

2. In our app:
```javascript
const webAuth = new auth0.WebAuth({
  domain: 'ourDomain.auth0.com',
  clientID: 'OUR_CLIENT_ID',
  postMessageDataType: 'custom-type'
});
```
3. In the callback handler page (a complete separate page)
```html
<!DOCTYPE html>
<html>
  <head>
    <script type="text/javascript">
      parent.postMessage({
        hash: window.location.hash,
        type: 'custom-type'
      }, window.location.origin.concat('/'));
    </script>
  </head>
  <body></body>
</html>
```

And still getting the iframe closed by other browser extensions.

**Comment by luisrudge** [comment] 2017-07-05 22:06
Can you build a sample repo where I can reproduce this issue? It'd be good to have the dependencies that use postMessage as well so I can reproduce on my machine too.

**Comment by buccfer** [comment] 2017-07-06 00:48
I think it would be better if you can give us a working example, since we don't really know how we should implement the renew auth in the new flow. 

The thing is that is you have a browser extension like vue-dev-tools or similar, the iframe is still being closed by the browser extension with the authReault having useless data.

**Comment by aaronchilcott** [comment] 2017-07-06 01:15
@buccfer, If your development extensions are causing issues then I recommend turning them off while developing a prototype. 

Here's some snippets from some working code I used when I developed the original patch for this functionality:

Callback html page:


    <!DOCTYPE html>
    <html>
    <head>
      <script type="text/javascript">
        var data = {
          type: 'auth0:silent-authentication',
          hash: window.location.hash
        };

        // This page is designed to be loaded in an Iframe
        parent.postMessage(data, "*");
      </script>
    </head>
    <body></body>
    </html>


This part is written in typescript, but the general gist of the code should be clear:


      public loginSso(): void {
        var data = {
          audience: `https://${AUTH_CONFIG.domain}/userinfo`,
          scope: 'openid',
          responseType: 'id_token token',
          usePostMessage: true,
          postMessageDataType: 'auth0:silent-authentication',
          redirectUri: AUTH_CONFIG.silentCallbackURL,
        };
    
        this.notifications.show(
          'Checking for an existing SSO Session',
          NotificationService.TYPES.INFO
        );
    
        this.auth0.renewAuth(data, (err, authResult)=>{
    
          console.log(data, err, authResult);
    
    
          if (err && err.error == 'login_required') {
            this.notifications.show(
              'No existing SSO sessions found, redirecting you to sign-on server.',
              NotificationService.TYPES.WARNING
            );
    
            setTimeout(() => {
              this.login()
            }, 3000);
          } else if (err) {
            this.notifications.show(
              'Something went wrong while attempting to perform SSO Signon',
              NotificationService.TYPES.ERROR
            );
            return
          }
    
          if (authResult && authResult.accessToken && authResult.idToken) {
            this.setSession(authResult);
    
            this.notifications.show(
              'Existing SSO Session found! You are now authenticated .',
              NotificationService.TYPES.INFO
            );
    
          } else if (err && err.error == 'login_required') {
            this.notifications.show(
              'No existing SSO sessions found, redirecting you to sign-on server.',
              NotificationService.TYPES.WARNING
            );
    
            setTimeout(() => {
              this.login()
            }, 3000);
          } else {
            // There is a possible bug in the auth0 library. For now we don't want to show this.
            this.notifications.show(
              'An unexpected error has occurred.',
              NotificationService.TYPES.ERROR,
              3000
            );
          }
        });
      }

**Comment by shorn** [comment] 2017-07-06 04:11
Just some feedback to let people know luisrudge's code sample above worked perfectly for me. 
I was getting an iframe error reported because of "webpackOk" message before implementing the 'postMessageDataType' attribute.
Using autho0-lock v10.18.0.

**Comment by luisrudge** [comment] 2017-07-06 13:05
@buccfer @gilesbutler I noticed you both are not using `usePostMessage: true,`. Maybe that's the issue? Let's track this down so we can either improve docs or fix the bug if there is one.

**Comment by luisrudge** [comment] 2017-07-06 13:08
although @shorn said my example works and I didn't use it as well, so that may not be the issue.

**Comment by buccfer** [comment] 2017-07-06 13:17
@luisrudge code:
```javascript
var auth0 = new auth0.WebAuth({
  domain: "{YOUR_AUTH0_DOMAIN}",
  clientID: "{YOUR_AUTH0_CLIENT_ID}",
  postMessageDataType: 'my-custom-data-type'
});
```
@aaronchilcott code:
```javascript
var data = {
      audience: `https://${AUTH_CONFIG.domain}/userinfo`,
      scope: 'openid',
      responseType: 'id_token token',
      usePostMessage: true,
      postMessageDataType: 'auth0:silent-authentication',
      redirectUri: AUTH_CONFIG.silentCallbackURL,
    };

    this.auth0.renewAuth(data, (err, authResult)=>{
```
I see they are different. In one the postMessageDataType is in the auth0.WebAuth constructor and in the other it is in the renewAuth options.
I'll see if the second approach works, since the first one doesn't. But I have to wait till the afternoon for that.

**Comment by shorn** [comment] 2017-07-06 23:12
@luisrudge - sorry, I just meant the `postMessageDataType` works.  My code that calls `renewAuth()` **does** have `usePostMessage:true`.

**Comment by buccfer** [comment] 2017-07-07 15:47
@shorn Can you please share your implementation? Since none of the examples found so far work for me. Have you tested it with browser extensions like vue-dev-tools or augury? They still close the iframe with useless data. 

@aaronchilcott What's the point in disabling the extensions? Shouldn't auth0js work independently of the browser extensions the user has enabled? That's something you cannot control in production.

@luisrudge Is there any chance to update the doc?

**Comment by luisrudge** [comment] 2017-07-07 16:12
@buccfer it should work despite extensions. Please create a sample with a list of extensions so I can reproduce the issue. Please include the steps I have to follow to cause the issue (like: click to open the popup, then click the XYZ button in the extension etc)

**Comment by buccfer** [comment] 2017-07-07 17:01
@luisrudge Finally I got something different. Now the renewAuth gives me an error:

`{error: "invalid_token", errorDescription: "Algorithm HS256 is not supported. (Expected algs: [RS256])"}`

Do I have to configure the option to switch how the id_tokens are signed from HS256 to RS256 in our client?

**Comment by luisrudge** [comment] 2017-07-07 17:06
Correct. There's a similar discussion here: https://github.com/auth0/auth0.js/issues/303#issuecomment-273851977

**Comment by dimitrovs** [comment] 2017-07-22 23:25
The `postMessageDataType` has to be in the renewAuth options, not in auth0.WebAuth . Then it works with 8.8.0 .

**Comment by devpascoe** [comment] 2017-08-14 05:28
☝️ yes @dimitrovs that <3

**Comment by luisrudge** [comment] 2017-08-14 12:31
@dimitrovs you're totally write. I'll edit my snippet to reflect that. thanks!

**Comment by skunkwerk** [comment] 2017-09-12 21:58
Thank God I found this thread.  Spent 9 hours trying to debug this issue with renewAuth.  Turns out it was one of the chrome developer tools - likely Vue.js debugger.  Turn it off, and it works fine!

**Comment by Geczy** [comment] 2017-09-29 18:33
This was very annoying, thank you for the direction. I've submitted a PR to fix this in the auth0 examples too https://github.com/auth0-samples/auth0-react-samples/pull/44
