### ISSUE TITLE
DecodeJwt doesn't verify the ID token

### ISSUE THREAD

**Issue by alexanderkiel** [auth0/auth0.js#175] opened 2016-07-07 16:49 UTC
I'm really surprised that decodeJwt doesn't verify the ID token at all.

```js
Auth0.prototype.decodeJwt = function (jwt) {
  var encoded = jwt && jwt.split('.')[1];
  return json_parse(Base64Url.decode(encoded));
};
```

I would like to use Auth0 with a single page app and the implicit flow. There is is essential to verify the ID token using the Auth0 public key. On top of that OpenID Connect 1.0 requires the use of a nonce.

**Comment by hzalaz** [comment] 2016-09-12 20:34
Closing this one. Since it's only decoding (not verifying) it's the expected behaviour of the method. If the token should be verified with the public key you could take it from the result and validate it using one of the libraries in https://jwt.io.

**Closed by hzalaz** 2016-09-12 20:34 UTC
