### ISSUE TITLE
Login methods without getProfile()

### ISSUE THREAD

**Issue by IvanRave** [auth0/auth0.js#62] opened 2015-02-02 05:07 UTC
I need only id_token after Login (user + pass and trough social networks)
without additional requests to get profile info

**Comment by mgonto** [comment] 2015-02-02 14:25
Hey @IvanRave,

If you're using Redirect Mode (not showing the popup), it'll only get the id_token for you. If you're using a popup, the profile is gotten automatically. It still shouldn't bother you in your flow if you only need id_token.

Does that help?

Thanks!

**Comment by IvanRave** [comment] 2015-02-02 15:44
Thx for a quick answer, @mgonto 

This additional request in a callback and waste time of users
Especially for slow connections: 
GPRS 50Kbps:  approximately 1.6 seconds

**Comment by mgonto** [comment] 2015-02-02 15:59
We'll take a look at this to see the best way to accomplish both having the profile easily as well as working with slow connections.

For now, I'd recommend using redirect mode.

Cheers!

**Comment by pose** [comment] 2015-02-19 14:21
Duplicate of #42

**Closed by pose** 2015-02-19 14:21 UTC
