### ISSUE TITLE
Refresh Token is null

### ISSUE THREAD

**Issue by danouche93** [auth0/auth0.js#1189] opened 2021-06-28 10:32 UTC
### Describe the problem

When using auth0.WebAuth.authorize, I receive the access token as expected but the refresh token is null so I cannot use it to refresh the access token. So when I want to call my API and the access token is expired, my API returns me an error 401 Unauthorized.

### What was the expected behavior?

I expected the authorize to return a refresh token in order to refresh the access token that have an expiration of 2 hours.

### Reproduction

I use Angular and this is how I'm doing it : 
```
auth0 = new auth0.WebAuth({
    clientID: 'xxxxxxxxxxx',
    domain: 'xxxxxxxx',
    responseType: 'token id_token',
    audience: 'https://xxxxx.auth0.com/api/v2/',
    redirectUri: environment.websiteUrl + 'callback',
    scope: 'openid email profile offline_access'
  });

  public login(): void {
    this.auth0.authorize({
      connection: "Username-Password-Authentication"
    });
  }
```
and this is what it returns 

![image](https://user-images.githubusercontent.com/50110805/123621393-d259a280-d813-11eb-8035-a3422f49f398.png)

In the API of auth0, I allowed offline access to get the refresh token.

### Environment

Angular  6.1.10
Angular CLI 6.2.9
Typescript ~2.9.2
Auth0-js ^9.13.4

**Comment by stevehobbsdev** [comment] 2021-06-30 10:55
Thanks for the report @danouche93. This is a security limitation from Auth0 Server, that when using the Implicit Flow with query to authorize your users (as happens when using this SDK), refresh tokens are not issued. This is because tokens are returned to your app in the URL, and refresh tokens could easily be leaked (in browser history, etc).

As you're using Angular 6, there isn't so much we can do for you here unless you're also using some kind of backend. We do have an [Angular SDK](https://github.com/auth0/auth0-angular/) but only supports Angular 9+.

Closing for now, but happy to continue the discussion if you have further questions.

**Closed by stevehobbsdev** 2021-06-30 10:55 UTC
Labels: bug report

**Comment by danouche93** [comment] 2021-06-30 11:09
Thanks for your answer @stevehobbsdev
I understand now why I don't get a refresh token. So now I use the checkSession function to get a new token when the old one expired. Is there a limit using this ? Or it works the same as a refresh token ?

**Comment by stevehobbsdev** [comment] 2021-07-02 07:22
Unfortunately it depends on the browsers your using. `checkSession` is fine to use but the problem is it relies on your browser supporting third-party cookies. So it will not work in browsers that actively block third-party cookies, such as Safari and Brave. I think Firefox will be blocking these soon if they haven't already, and [Chrome will be blocking these in the future](https://www.cookiebot.com/en/google-third-party-cookies/).

You have two options:

* Use [rotating refresh tokens](https://auth0.com/docs/tokens/refresh-tokens/refresh-token-rotation) but these are not supported by this SDK thanks to it using the implicit flow as described above - you will need to migrate to [`auth0-angular`](https://github.com/auth0/auth0-angular) or [`auth0-spa-js`](https://github.com/auth0/auth0-spa-js).
* Use a [custom domain](https://auth0.com/docs/custom-domains), but this is a paid Auth0 feature

Hope that helps
